
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { Lead } from './types';

interface ReportData {
    lead: Lead;
    clinicName: string;
    doctorName: string;
    diagnosis: string;
    protocol: string;
    priceEstimate: string;
    validUntil: string;
    lang?: 'tr' | 'en' | 'ar';
}

const TRANSLATIONS = {
    en: {
        title: 'OFFICIAL MEDICAL TREATMENT PROPOSAL',
        patient: 'Patient',
        date: 'Date',
        aiAnalysis: 'AI Preliminary Analysis',
        tableHead: ['Phase', 'Procedure', 'Duration', 'Notes'],
        tableBody: [
            ['1. Pre-Op', 'Consultation & Blood Tests', '1 Day', 'Included'],
            ['3. Post-Op', 'Recovery & Washing', '2 Days', 'Hotel Included']
        ],
        totalCost: 'Total Estimated Cost',
        includes: 'Includes: Surgery, VIP Transfer, 5-Star Hotel (3 Nights), Medication.',
        validUntil: 'Offer Valid Until',
        disclaimer: 'Disclaimer: This is a preliminary proposal generated by Aura OS Artificial Intelligence based on provided images. Final medical assessment will be performed by the surgeon upon physical examination.',
        poweredBy: 'Powered by Aura Health OS v4.0'
    },
    tr: {
        title: 'RESMİ TIBBİ TEDAVİ TEKLİFİ',
        patient: 'Hasta Adı',
        date: 'Tarih',
        aiAnalysis: 'Yapay Zeka Ön Analizi',
        tableHead: ['Faz', 'İşlem', 'Süre', 'Notlar'],
        tableBody: [
            ['1. Hazırlık', 'Konsültasyon & Kan Testleri', '1 Gün', 'Dahil'],
            ['3. Operasyon Sonrası', 'İyileşme & Yıkama', '2 Gün', 'Otel Dahil']
        ],
        totalCost: 'Tahmini Toplam Tutar',
        includes: 'Dahil Olanlar: Operasyon, VIP Transfer, 5-Yıldızlı Otel (3 Gece), İlaçlar.',
        validUntil: 'Teklif Geçerlilik Tarihi',
        disclaimer: 'Yasal Uyarı: Bu teklif, sağlanan görseller üzerinden Aura OS Yapay Zekası tarafından oluşturulmuş ön taslaktır. Kesin tedavi planı, cerrahın fiziksel muayenesi sonrası netleşecektir.',
        poweredBy: 'Aura Health OS v4.0 Altyapısı'
    }
};

export const generateMedicalReport = (data: ReportData) => {
    const doc = new jsPDF();
    const { lead, clinicName, doctorName, diagnosis, protocol, priceEstimate, validUntil } = data;

    const t = TRANSLATIONS[data.lang === 'tr' ? 'tr' : 'en']; // Default to EN

    // 1. Header (Brand)
    doc.setFillColor(0, 0, 0); // Black Header
    doc.rect(0, 0, 210, 40, 'F');

    doc.setTextColor(255, 255, 255);
    doc.setFontSize(22);
    doc.setFont('helvetica', 'bold');
    doc.text(clinicName, 20, 25);

    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.text(t.title, 20, 33);

    // 2. Patient Info
    doc.setTextColor(0, 0, 0);
    doc.setFontSize(12);
    doc.text(`${t.patient}: ${lead.name}`, 20, 60);
    doc.text(`ID: ${lead.phone}`, 20, 68); // Using phone as unique ID for now
    doc.text(`${t.date}: ${new Date().toLocaleDateString()}`, 150, 60);

    // 3. AI Diagnosis Section
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text(t.aiAnalysis, 20, 90);


    doc.setFontSize(11);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(60, 60, 60);

    const splitDiagnosis = doc.splitTextToSize(diagnosis, 170); // Wrap text
    doc.text(splitDiagnosis, 20, 100);

    // 4. Treatment Protocol Table
    // Using autoTable for nice formatting
    let tableStartY = 100 + (splitDiagnosis.length * 5) + 20;

    autoTable(doc, {
        startY: tableStartY,
        head: [t.tableHead],
        body: [
            t.tableBody[0],
            ['2. Operation', protocol, '4-6 Hours', 'Local Anesthesia'], // Protocol comes from dynamic data
            t.tableBody[1],
        ],
        headStyles: { fillColor: [0, 0, 0] }, // Black header
        theme: 'grid'
    });

    // 5. Price Estimate
    // @ts-ignore
    let finalY = doc.lastAutoTable.finalY + 20;

    doc.setFillColor(245, 245, 245); // Light Gray Box
    doc.roundedRect(20, finalY, 170, 40, 3, 3, 'F');

    doc.setFontSize(16);
    doc.setTextColor(0, 0, 0);
    doc.setFont('helvetica', 'bold');
    doc.text(`${t.totalCost}: ${priceEstimate}`, 30, finalY + 15);

    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(100, 100, 100);
    doc.text(t.includes, 30, finalY + 25);
    doc.text(`${t.validUntil}: ${validUntil}`, 30, finalY + 32);

    // 6. Footer / Disclaimer
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    const disclaimer = t.disclaimer;
    const splitDisclaimer = doc.splitTextToSize(disclaimer, 170);
    doc.text(splitDisclaimer, 20, 270);

    doc.text(t.poweredBy, 160, 280);

    // Return Blob URL (or save directly)
    return doc;
};
