@echo off
set NEXT_PUBLIC_SUPABASE_URL=https://wdrvtoklnhvpxzceppsn.supabase.co
set NEXT_PUBLIC_SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndkcnZ0b2tsbmh2cHh6Y2VwcHNuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjY2MDE2ODQsImV4cCI6MjA4MjE3NzY4NH0.8CbyDjDkQPYKOXG6r_PDeK1GUKUU2jzgDsraSowQ6Vc
npx tsx verify-referral.ts
